version: "3"
services:
  mongodb:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  express:
    image: ariefdarmawant/express-update:latest
    depends_on:
      - mongodb
    # build: ./
    environment:
      - DB_HOST=mongodb
      - DB_NAME=CRUDmongo
      - DB_PORT=27017
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
